version: "3"
services:
  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_DATABASE=movies
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=clave
    ports:
      - "3306:3306"

  myadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOST=mysql:3306
    links:
      - mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

  movies:
    image: "fervillano/movies:1.1"
    ports:
      - "3500:3500"
    links:
      - mysql
    depends_on:
      - mysql